make sure we are on the correct branch before git tagging

diff --git a/git-hf-hotfix b/git-hf-hotfix
--- a/git-hf-hotfix
+++ b/git-hf-hotfix
@@ -328,6 +328,8 @@ cmd_finish() {
 	fi
 
 	if noflag notag; then
+		# first pull the correct branch
+		git checkout "$BRANCH" || die "Could not check out $BRANCH."
 		# try to tag the release
 		# in case a previous attempt to finish this release branch has failed,
 		# but the tag was set successful, we skip it now
